config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  FOODTYPE = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: FOODTYPE }
end

app/models/review.rb
class Review < ApplicationRecord
  STARS = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: STARS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.all
  end
  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save!
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to new_restaurant_path
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to new_restaurant_review_path(@restaurant_params)
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurant_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  def index
    @reviews = Review.all
  end
  def show
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant_id = params[:restaurant_id]
    if @review.save!
      redirect_to restaurant_path(@review.restaurant_id)
    else
      redirect_to new_restaurant_review_path(review_params)
    end
  end

  def edit
  end

  def update
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  def destroy
    @review.destroy
    redirect_to review_path
  end

  private

  def review_params
    params.require(:review).permit(:restaurant, :content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class = "container">
  <%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::FOODTYPE %>
    <%= f.button :submit, class: 'btn btn-primary w-100' %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class = "p-3">
  <h1>Restaurants</h1>

  <% @restaurants.each do |restaurant| %>
  <div class = "card-body border p-3 mb-2">
    <h4 class = "card-title"><%= restaurant.name %></h4>
    <p class = "card-subtitle">  <%= restaurant.address %> </p>
    <p class="card-text">Food Type:  <%= restaurant.category %></p>
    <p class="card-text"> <%= restaurant.reviews %> </p>
    <%= link_to "See details", restaurant_path(restaurant) %>
  </div>
  <% end %>

  <%= link_to "Create a New Restaurant", new_restaurant_path  %>
</div>

app/views/restaurants/new.html.erb
<div class = "container">
  <%= render 'form', restaurant: @restaurant %>
  <p class = "p-3"><%= link_to "Back to list", restaurants_path  %></p>
</div>

app/views/restaurants/show.html.erb
<div class = "card-body border p-3 mb-2">
  <h2 class = "card-title"><%= @restaurant.name %></h2>
  <p class = "card-subtitle"> Address:  <%= @restaurant.address %> </p>
  <p class="card-text">Food Type:  <%= @restaurant.category %></p>
  <p class="card-text"> <%= @restaurant.reviews.first%></p>
  <p><%= link_to "Add a Review", new_restaurant_review_path(@restaurant) %></p>
  <p><%= link_to "Back to list", restaurants_path  %></p>
</div>

app/views/reviews/_form.html.erb
<div class = "container">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: Review::STARS %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>
</div>

app/views/reviews/edit.html.erb
<%= render 'form', review: @review %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<% @Reviews.each do |review| %>
  <h4><%= review.content %></h4>
  <p>  <%= "*" * review.rating %> </p>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>